
```{r packages}
library(Hmisc)
library(mice)
```

```{r path}
path <- ".../Analysis projects/CKB exposome"
path2 <- ".../UKB/Analysis projects/ACM EWAS 2021"

```

```{r import}

# load data
endpoints <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/endpoints.csv")
dat <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/data_baseline_questionnaires.csv")

# load definitions
end_definitions <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/endpoint_definitions.csv")
column_details <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/data_dictionary.csv")
exp_details <- column_details[which(column_details$table == "data_baseline_questionnaires"), ]

value_definitions <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/value_definitions.csv")

resurvey_devices <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/data_resurvey2_devices.csv")
resurvey_dat <- read.csv("/Users/aargenti/Documents/proteomic_age/data/ckb/DAR-2023-00293-V1/data_resurvey2_questionnaires.csv")
```

```{r identify_columns}
ordered_cols <- c(
  Cs(
    alc_morning,
    alc_weekly,
    alc_year,
    bowel_movement_freq,
    cidi_a15,
    cidi_a1a,
    cidi_a1b,
    cidi_a3a,
    cidi_b17,
    cidi_b8,
    cidi_b9,
    cooking_freq_before_prev,
    cooking_freq_present,
    cooking_freq_prev,
    copd_spirometry_severity,
    cough_freq,
    cough_sputum_morning,
    diet_freq_dairy,
    diet_freq_eggs,
    diet_freq_fish,
    diet_freq_fresh_fruit,
    diet_freq_fresh_veg,
    diet_freq_meat,
    diet_freq_other_staple,
    diet_freq_poultry,
    diet_freq_preserved_veg,
    diet_freq_rice,
    diet_freq_soybean,
    diet_freq_wheat,
    diet_spice,
    diet_spice_strength,
    gum_bleed_freq,
    heavy_phys_freq,
    highest_education,
    household_income,
    leisure_exercise_freq,
    satisfaction_level,
    self_rated_health,
    slow_b_before_prev,
    slow_b_present,
    slow_b_prev,
    smoke_exposure,
    smoking_now,
    smoking_past,
    tea_strength,
    tea_weekly,
    tea_year
  )
)

unordered_cols <- c(
  Cs(
    alc_intake_change,
    alc_phys_reaction,
    alc_time_of_day,
    alc_typ_day_kind,
    alcohol_category,
    cancer_site,
    chimney_before_prev,
    chimney_present,
    chimney_prev,
    cidi_a2,
    cidi_b2,
    cidi_b2a,
    cidi_b2b,
    cidi_b5,
    comparative_health,
    cooking_fuel_before_prev,
    cooking_fuel_present,
    cooking_fuel_prev,
    cooking_oil_before_prev,
    cooking_oil_present,
    cooking_oil_prev,
    ever_lived_with_smoker,
    father_still_alive,
    heating_fuel_before_prev,
    heating_fuel_present,
    heating_fuel_prev,
    hep_b,
    main_exercise_type,
    marital_status,
    menopause_status,
    mother_still_alive,
    occupation,
    other_job_act_level,
    pill_use,
    region_code,
    season_work_kind,
    sleep_daytime_naps,
    sleep_snoring,
    slow_b_fuel_before_prev,
    slow_b_fuel_present,
    slow_b_fuel_prev,
    slow_b_loc_before_prev,
    slow_b_loc_present,
    slow_b_loc_prev,
    smoking_category,
    smoking_change,
    smoking_first_kind,
    smoking_inhalation,
    smoking_stopped_reason,
    tea_intake_change,
    tea_kind_most,
    tea_temperature,
    walking_short_of_breath,
    walking_slow_down,
    winter_smoke,
    winter_smoke_stop,
    work_activity_level,
    work_journey_mode,
    weight_changed
  )
)

```

```{r factor_recoding}

# get binary columns
bins <- exp_details$column_name[which(exp_details$value_type == "no_yes")]

# get ordered columns
ords <- exp_details$column_name[which(exp_details$contents == "Categorised")]
ords <- ords[ords %nin% bins]
ords <- ords[ords %nin% unordered_cols]

# get unordered columns
unords <- exp_details$column_name[which(exp_details$contents == "Categorised")]
unords <- unords[unords %nin% bins]
unords <- unords[unords %nin% ordered_cols]

# get all categorical columns
facts <- exp_details$column_name[which(exp_details$contents == "Categorised")]

# recode binaries as factors
for (k in seq_along(bins)) {
  # don't run in variables with no variance
  if (0 %in% unique(dat[[bins[k]]]) &
      1 %in% unique(dat[[bins[k]]])) {
    
    # get value type for label recode
    key <- exp_details$value_type[which(exp_details$column_name == colnames(dat[bins[k]]))]
    # get reference table for value type
    level_ref <- value_definitions[which(value_definitions$value_type == key), ]
    
    dat[[bins[k]]] <- factor(dat[[bins[k]]], ordered = FALSE, 
                             levels = level_ref$value,
                             labels = level_ref$definition)
    dat[[bins[k]]] <- relevel(dat[[bins[k]]], ref = "No")
    
  }
}

# recode ordered factors
for (k in seq_along(ords)) {
  
  # get value type for label recode
  key <- exp_details$value_type[which(exp_details$column_name == colnames(dat[ords[k]]))]
  # get reference table for value type
  level_ref <- value_definitions[which(value_definitions$value_type == key), ]
  
  dat[[ords[k]]] <- factor(dat[[ords[k]]], ordered = TRUE,
                           levels = level_ref$value,
                           labels = level_ref$definition)
}

# recode unordered factors
for (k in seq_along(unords)) {
  # get value type for label recode
  key <- exp_details$value_type[which(exp_details$column_name == colnames(dat[unords[k]]))]
  # get reference table for value type
  level_ref <- value_definitions[which(value_definitions$value_type == key), ]
  
  dat[[unords[k]]] <- factor(dat[[unords[k]]], ordered = FALSE,
                             levels = level_ref$value,
                             labels = level_ref$definition)
  reference <- names(sort(table(dat[[unords[k]]]))[nlevels(dat[[unords[k]]])])
  dat[[unords[k]]] <- relevel(dat[[unords[k]]], ref = reference)
}

```

```{r numeric_recoding}

content <- unique(exp_details$contents)
exclude <- c(
  "Two digit day",
  "Two digit hour (24 hour clock)",
  "Two digit month",
  "HH:mm:ss",
  "DD/MM/YYYY", 
  "DD/MM/YYYY HH:mm:ss",
  "Categorised",
  "3 digit code of staff member who completed this section's measurements",
  "Text (English)",
  "1=Yes, 0=No",
  "Numeric code of the staff member who completed the questionnaire with the subject",
  "0=Yes, 1=No",
  "1=Female, 0=Male",
  "1=urban, 0=rural",
  "Always 15",
  ""
)

nums <- content[which(content %nin% exclude)]
num_cols <- exp_details$column_name[which(exp_details$contents %in% nums)]

# recode numeric variables
for (k in seq_along(num_cols)) {
  dat[[num_cols[k]]] <- as.numeric(dat[[num_cols[k]]])
}

```

```{r endpoint_merge}

# merge
dat <- merge(
  dat,
  endpoints,
  by = 'csid'
)

```

```{r recode_exposures}

## recoding variables not caught by generic methods above

# set reference for reverse coded binary
dat$diet_shortage_lost_weight <- factor(dat$diet_shortage_lost_weight,
                                        ordered = FALSE)
dat$diet_shortage_lost_weight <- relevel(dat$diet_shortage_lost_weight,
                                         ref = "1")


## diet variables were reverse coded and need to be changed
diet_vars <- column_details$column_name[grep("diet_freq", column_details$column_name)]
for (k in seq_along(diet_vars)) {
    dat[[diet_vars[k]]] <- factor(dat[[diet_vars[k]]], ordered = TRUE,
                                  levels = rev(levels(dat[[diet_vars[k]]])))
}

# sex
dat$is_female <- factor(dat$is_female, ordered = FALSE,
                        levels = c(0,1),
                        labels = c("No", "Yes"))

dat$is_female <- relevel(dat$is_female, 
                         ref = "No")

# COPD
dat$copd <- factor(dat$copd, ordered = FALSE,
                   levels = c(0,1),
                   labels = c("No", "Yes"))


dat$copd <- relevel(dat$copd, ref = "No")

# urban region
dat$region_is_urban <- factor(dat$region_is_urban, 
                              ordered = FALSE)

sort(table(dat$region_is_urban))

dat$region_is_urban <- relevel(dat$region_is_urban, ref = "0")

# weight at age 25 - convert to kg
dat$age_25_weight_kg <- dat$age_25_weight_jin * 0.50
summary(dat$age_25_weight_kg)

# age at recruitment - convert to decimal
dat$age_at_study_date <- dat$age_at_study_date_x100 / 100
summary(dat$age_at_study_date)

# recode hours of work to make 0 if not employed (remove nested status)
dat$work_hours_recode <- dat$work_hours_per_week
dat$work_hours_recode[which(dat$occupation %in% c("Retired","House wife / husband","Unemployed"))] <- 0
dat$work_hours_recode[which(dat$work_activity_level == "Retired or housewife/husband or unemployed or disabled")] <- 0

# recode mins of travel time to work to make 0 if not employed (remove nested status)
dat$work_journey_recode <- dat$work_journey_mins
dat$work_journey_recode[which(dat$occupation %in% c("Retired","House wife / husband","Unemployed"))] <- 0
dat$work_journey_recode[which(dat$work_activity_level == "Retired or housewife/husband or unemployed or disabled")] <- 0

# harmonized employment variables
dat$employment_travel_time <- 
    ifelse(
        dat$occupation == "Agriculture & related workers",
        dat$farm_work_journey_mins,
        dat$work_journey_recode
    )

dat$employment_weekly_hours <- 
    ifelse(
        dat$occupation == "Agriculture & related workers",
        dat$field_work_hours_per_week,
        dat$work_hours_recode
    )

# smoking status
dat$smoking_status <- NA
dat$smoking_status[which(dat$smoking_now != "Do not smoke now")] <- "Current"
dat$smoking_status[which(dat$smoking_past != "Did not smoke") &
                       dat$smoking_now == "Do not smoke now"] <- "Former"
dat$smoking_status[which(dat$smoking_now == "Do not smoke now" & 
                             dat$smoking_past == "Did not smoke")] <- "Never"

dat$smoking_status <- factor(dat$smoking_status, ordered = FALSE)
reference <- names(sort(table(dat$smoking_status))[nlevels(dat$smoking_status)])
dat$smoking_status <- relevel(dat$smoking_status, ref = reference)

# sleep hours
dat$sleep_hours_categorical <-
    ifelse(
        dat$sleep_hours < 7,
        '<7 hours',
        ifelse(
            dat$sleep_hours >= 7 &
                dat$sleep_hours < 9,
            '7-9 hours',
            ifelse(
                dat$sleep_hours >= 9,
                '>9 hours',
                NA
            )
        )
    )

dat$sleep_hours_categorical <- 
    factor(dat$sleep_hours_categorical, 
           levels = c('<7 hours',
                      '7-9 hours',
                      '>9 hours'),
           ordered = FALSE)

dat$sleep_hours_categorical <- 
    relevel(dat$sleep_hours_categorical, 
            ref = '7-9 hours')

```

```{r recode_outcomes}
## dates
library(lubridate)

# class censoring date as date
head(dat$censoring_date)
dat$censoring_date <- ymd_hms(dat$censoring_date)
dat$censoring_date <- as.Date(dat$censoring_date)
head(dat$censoring_date)

# class recruitment date as date
head(dat$study_date)
dat$study_date <- ymd_hms(dat$study_date)
dat$study_date <- as.Date(dat$study_date)
head(dat$study_date)

# class all stroke diagnosis date as date
head(dat$ep_CKB0070_combined_datedeveloped)
dat$ep_CKB0070_combined_datedeveloped <- ymd_hms(dat$ep_CKB0070_combined_datedeveloped)
dat$ep_CKB0070_combined_datedeveloped <- as.Date(dat$ep_CKB0070_combined_datedeveloped)
head(dat$ep_CKB0070_combined_datedeveloped)

# class ischemic stroke diagnosis date as date
head(dat$ep_CKB0009_combined_datedeveloped)
dat$ep_CKB0009_combined_datedeveloped <- ymd_hms(dat$ep_CKB0009_combined_datedeveloped)
dat$ep_CKB0009_combined_datedeveloped <- as.Date(dat$ep_CKB0009_combined_datedeveloped)
head(dat$ep_CKB0009_combined_datedeveloped)

# class diabetes diagnosis date as date
head(dat$ep_CKB0048_combined_datedeveloped)
dat$ep_CKB0048_combined_datedeveloped <- ymd_hms(dat$ep_CKB0048_combined_datedeveloped)
dat$ep_CKB0048_combined_datedeveloped <- as.Date(dat$ep_CKB0048_combined_datedeveloped)
head(dat$ep_CKB0048_combined_datedeveloped)

# class IHD diagnosis date as date
head(dat$ep_CKB0003_combined_datedeveloped)
dat$ep_CKB0003_combined_datedeveloped <- ymd_hms(dat$ep_CKB0003_combined_datedeveloped)
dat$ep_CKB0003_combined_datedeveloped <- as.Date(dat$ep_CKB0003_combined_datedeveloped)
head(dat$ep_CKB0003_combined_datedeveloped)

# class chronic liver diagnosis date as date
head(dat$ep_CKB0105_combined_datedeveloped)
dat$ep_CKB0105_combined_datedeveloped <- ymd_hms(dat$ep_CKB0105_combined_datedeveloped)
dat$ep_CKB0105_combined_datedeveloped <- as.Date(dat$ep_CKB0105_combined_datedeveloped)
head(dat$ep_CKB0105_combined_datedeveloped)

# class chronic kidney diagnosis date as date
head(dat$ep_CKB0062_combined_datedeveloped)
dat$ep_CKB0062_combined_datedeveloped <- ymd_hms(dat$ep_CKB0062_combined_datedeveloped)
dat$ep_CKB0062_combined_datedeveloped <- as.Date(dat$ep_CKB0062_combined_datedeveloped)
head(dat$ep_CKB0062_combined_datedeveloped)

# class COPD diagnosis date as date
head(dat$ep_CKB0033_combined_datedeveloped)
dat$ep_CKB0033_combined_datedeveloped <- ymd_hms(dat$ep_CKB0033_combined_datedeveloped)
dat$ep_CKB0033_combined_datedeveloped <- as.Date(dat$ep_CKB0033_combined_datedeveloped)
head(dat$ep_CKB0033_combined_datedeveloped)


## survival time
dat$ACM_survival_time <- as.numeric(dat$censoring_date - dat$study_date)
dat$censor_age <- dat$age_at_study_date + (dat$ACM_survival_time / 365.25)

## mortality indicator
dat$ACM_event_indicator <- NA
dat$ACM_event_indicator[which(dat$censoring_reason == "Dead                          ")] <- 1
dat$ACM_event_indicator[which(is.na(dat$ACM_event_indicator))] <- 0



## all stroke
dat$all_stroke <- dat$ep_CKB0070_combined_ep

# prevalent
dat$prevalent_all_stroke <- 0
index <- which(dat$ep_CKB0070_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$stroke_or_tia_diag == "Yes")
dat$prevalent_all_stroke[index] <- 1
dat$prevalent_all_stroke[index2] <- 1

# incident
dat$incident_all_stroke <- ifelse(
  dat$prevalent_all_stroke == 1,
  NA,
  ifelse(
    dat$all_stroke == 1,
    1,
    0
  )
)

# censoring date
dat$all_stroke_censoring_date <- dat$censoring_date
dat$all_stroke_censoring_date[which(dat$all_stroke == 1)] <- dat$ep_CKB0070_combined_datedeveloped[which(dat$all_stroke == 1)]

# survival time
dat$all_stroke_survival_time <- as.numeric(dat$all_stroke_censoring_date - dat$study_date)


## ischemic stroke
dat$ischemic_stroke <- dat$ep_CKB0009_combined_ep

# prevalent
dat$prevalent_ischemic_stroke <- 0
index <- which(dat$ep_CKB0009_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$stroke_or_tia_diag == "Yes")
dat$prevalent_ischemic_stroke[index] <- 1
dat$prevalent_ischemic_stroke[index2] <- 1

# incident
dat$incident_ischemic_stroke <- ifelse(
  dat$prevalent_ischemic_stroke == 1,
  NA,
  ifelse(
    dat$ischemic_stroke == 1,
    1,
    0
  )
)

# censoring date
dat$ischemic_stroke_censoring_date <- dat$censoring_date
dat$ischemic_stroke_censoring_date[which(dat$ischemic_stroke == 1)] <- dat$ep_CKB0009_combined_datedeveloped[which(dat$ischemic_stroke == 1)]

# survival time
dat$ischemic_stroke_survival_time <- as.numeric(dat$ischemic_stroke_censoring_date - dat$study_date)



## type 2 diabetes
dat$diabetes <- dat$ep_CKB0048_combined_ep

# prevalent
dat$prevalent_diabetes <- 0
index <- which(dat$ep_CKB0048_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$diabetes_diag == "Yes")
dat$prevalent_diabetes[index] <- 1
dat$prevalent_diabetes[index2] <- 1

# incident
dat$incident_diabetes <- ifelse(
  dat$prevalent_diabetes == 1,
  NA,
  ifelse(
    dat$diabetes == 1,
    1,
    0
  )
)

# censoring date
dat$diabetes_censoring_date <- dat$censoring_date
dat$diabetes_censoring_date[which(dat$diabetes == 1)] <- dat$ep_CKB0048_combined_datedeveloped[which(dat$diabetes == 1)]

# survival time
dat$diabetes_survival_time <- as.numeric(dat$diabetes_censoring_date - dat$study_date)


## Chronic liver disease
dat$liver <- dat$ep_CKB0105_combined_ep

# prevalent
dat$prevalent_liver <- 0
index <- which(dat$ep_CKB0105_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$cirrhosis_hep_diag == "Yes")
dat$prevalent_liver[index] <- 1
dat$prevalent_liver[index2] <- 1

# incident
dat$incident_liver <- ifelse(
  dat$prevalent_liver == 1,
  NA,
  ifelse(
    dat$liver == 1,
    1,
    0
  )
)

# censoring date
dat$liver_censoring_date <- dat$censoring_date
dat$liver_censoring_date[which(dat$liver == 1)] <- dat$ep_CKB0105_combined_datedeveloped[which(dat$liver == 1)]

# survival time
dat$liver_survival_time <- as.numeric(dat$liver_censoring_date - dat$study_date)


## Chronic kidney disease
dat$kidney <- dat$ep_CKB0062_combined_ep

# prevalent
dat$prevalent_kidney <- 0
index <- which(dat$ep_CKB0062_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$kidney_dis_diag == "Yes")
dat$prevalent_kidney[index] <- 1
dat$prevalent_kidney[index2] <- 1

# incident
dat$incident_kidney <- ifelse(
  dat$prevalent_kidney == 1,
  NA,
  ifelse(
    dat$kidney == 1,
    1,
    0
  )
)

# censoring date
dat$kidney_censoring_date <- dat$censoring_date
dat$kidney_censoring_date[which(dat$kidney == 1)] <- dat$ep_CKB0062_combined_datedeveloped[which(dat$kidney == 1)]

# survival time
dat$kidney_survival_time <- as.numeric(dat$kidney_censoring_date - dat$study_date)



## type 2 diabetes
dat$IHD <- dat$ep_CKB0003_combined_ep

# prevalent
dat$prevalent_IHD <- 0
index <- which(dat$ep_CKB0003_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$chd_diag == "Yes")
dat$prevalent_IHD[index] <- 1
dat$prevalent_IHD[index2] <- 1

# incident
dat$incident_IHD <- ifelse(
  dat$prevalent_IHD == 1,
  NA,
  ifelse(
    dat$IHD == 1,
    1,
    0
  )
)

# censoring date
dat$IHD_censoring_date <- dat$censoring_date
dat$IHD_censoring_date[which(dat$IHD == 1)] <- dat$ep_CKB0003_combined_datedeveloped[which(dat$IHD == 1)]

# survival time
dat$IHD_survival_time <- as.numeric(dat$IHD_censoring_date - dat$study_date)


## COPD
dat$COPD <- dat$ep_CKB0033_combined_ep

# prevalent
dat$prevalent_COPD <- 0
index <- which(dat$ep_CKB0033_combined_datedeveloped <= dat$study_date)
index2 <- which(dat$copd == "Yes")
index3 <- which(dat$emph_bronc_diag == "Yes")
dat$prevalent_COPD[index] <- 1
dat$prevalent_COPD[index2] <- 1

# incident
dat$incident_COPD <- ifelse(
  dat$prevalent_COPD == 1,
  NA,
  ifelse(
    dat$COPD == 1,
    1,
    0
  )
)

# censoring date
dat$COPD_censoring_date <- dat$censoring_date
dat$COPD_censoring_date[which(dat$COPD == 1)] <- dat$ep_CKB0033_combined_datedeveloped[which(dat$COPD == 1)]

# survival time
dat$COPD_survival_time <- as.numeric(dat$COPD_censoring_date - dat$study_date)


```

```{r save}
library(feather)
write_feather(dat, "/Users/aargenti/Documents/proteomic_age/data/ckb/ckb_coded_data_oct_24_2023.feather")

# save
# save(dat, file = "K:/CKB-exposome/For_Austin/data/ckb_coded_data_oct_24_2023.RData")
write.csv(dat, row.names = FALSE, file = "/Users/aargenti/Documents/proteomic_age/data/ckb/ckb_coded_data_oct_24_2023.csv")

```
